name: ci-ations
on:
  workflow_run:
    workflows: [ "lint" ]
    types:
      - completed
  push:
    tags:
      - 'rc-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: aiiii
        run: echo 'aiiii'
      - name: install dependencies
        run: |
          cd ci-script
          npm install
      - name: ticket information update
        env:
          ID_TICKET: ${{ secrets.ID_TICKET }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          X_ORG_ID: ${{ secrets.X_ORG_ID }}
        run: |
          cd ci-script
          node ticketUpdate.js
